name: flutter_hands_on
description: A cool Flutter hands on.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.2
  dio: ^5.3.4
  meta: ^1.9.1
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/dash-hero.png
